//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

pub use super::exercises::Entity as Exercises;
pub use super::tasks::Entity as Tasks;
pub use super::users::Entity as Users;
pub use super::workout_sets::Entity as WorkoutSets;
