//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize, EnumIter, DeriveActiveEnum)]
#[sea_orm(rs_type = "String", db_type = "Enum", enum_name = "bodypart")]
pub enum Bodypart {
    #[sea_orm(string_value = "Abs")]
    Abs,
    #[sea_orm(string_value = "Back")]
    Back,
    #[sea_orm(string_value = "Biceps")]
    Biceps,
    #[sea_orm(string_value = "Chest")]
    Chest,
    #[sea_orm(string_value = "Legs")]
    Legs,
    #[sea_orm(string_value = "Shoulders")]
    Shoulders,
    #[sea_orm(string_value = "Triceps")]
    Triceps,
}
