//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.0

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "users")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(unique)]
    pub username: String,
    pub password: String,
    pub deleted_at: Option<DateTimeWithTimeZone>,
    #[sea_orm(column_type = "Text", nullable)]
    pub token: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub reset_code: Option<String>,
    pub is_email_verified: bool,
    #[sea_orm(column_type = "Text", nullable)]
    pub email_token: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::exercises::Entity")]
    Exercises,
    #[sea_orm(has_many = "super::workout_sets::Entity")]
    WorkoutSets,
}

impl Related<super::exercises::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Exercises.def()
    }
}

impl Related<super::workout_sets::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::WorkoutSets.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
